Flask_tutorial/pybo/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'Hello pybo!'

@bp.route('/')
def index():
    return redirect(url_for('question._list'))

Flask_tutorial/pybo/views/user_views.py
from flask import Blueprint, render_template, url_for, request, flash, session, g
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash, check_password_hash
from pybo import db
from pybo.models import User
from pybo.forms import UserForm, UserLoginForm
from datetime import datetime
import functools

bp = Blueprint('user', __name__, url_prefix='/user')

@bp.route('/create/', methods=('POST','GET'))
def user_create():
    form=UserForm()
    
    if request.method=='POST' and form.validate_on_submit():
        user=User.query.filter_by(user_name=form.user_name.data).first()
        if not user:
        
            user = User(user_name=form.user_name.data, password=generate_password_hash(form.password1.data), 
                        email=form.email.data, create_date=datetime.now())
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('user/user_create.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error=None
        user = User.query.filter_by(user_name=form.user_name.data).first()
        if not user:
            error = '존재하지 않는 아이디 입니다'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 틀렸습니다'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next','')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('user/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)
        
@bp.route('/logout')        
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method =='GET' else ''
            return redirect(url_for('user.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

Flask_tutorial/pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link
            rel="stylesheet"
            href="{{url_for('static', filename='bootstrap.min.css') }}" />
        <link
            rel="stylesheet"
            href="{{url_for('static', filename='style.css')}}" />
        <title>Hello, pybo!</title>
    </head>

    <body>
        {% include "navbar.html" %} {% block content %} {% endblock %}
        <script src="{{ url_for('static', filename='bootstrap.min.js')}}"></script>
        <!-- 자바스크립트 START -->
        {% block script %} {% endblock %}
        <!-- 자바스크립트 ENd -->
    </body>
</html>

Flask_tutorial/pybo/templates/form_error.html
<!-- 필드 오류-->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{form[field].label}}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}

<!-- Flash 오류-->
{% for messages in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">{{message}}</div>
{% endfor %}

Flask_tutorial/pybo/templates/navbar.html
<!-- 네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('main.index')}}">pybo</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <a class="nav-link" href="{{url_for('user.logout')}}"
                    >{{g.user.user_name}} (로그아웃)</a
                >
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.user_create')}}"
                        >계정생성</a
                    >
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.login')}}"
                        >로그인</a
                    >
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>